### ISSUE TITLE
Thanks and a question

### ISSUE THREAD

**Issue by matanox** [linushdot/unsafe-mode-menu#8]
Thanks a lot for this extension.

Is it safe to say that it boils down to [managing the unsafe mode attribute](https://github.com/linushdot/unsafe-mode-menu/blob/main/unsafe-mode-menu%40linushdot.local/extension.js#L44) without making any additional configuration changes to gnome?

It's quite an itch [not having screensharing](https://askubuntu.com/questions/1407494/screen-share-not-working-in-ubuntu-22-04-in-all-platforms-zoom-teams-google-m/1408030#1408030) and this seems to be the most natural solution.

**Comment by linushdot** [comment]
> Thanks a lot for this extension.

You're welcome

> Is it safe to say that it boils down to [managing the unsafe mode attribute](https://github.com/linushdot/unsafe-mode-menu/blob/main/unsafe-mode-menu%40linushdot.local/extension.js#L44) without making any additional configuration changes to gnome?

Yes. This is the only change to gnome (besides also showing a toggle button in the system menu). Since you referenced the code here, the unsafe mode actually is changed through these lines:
- [from toggle button](https://github.com/linushdot/unsafe-mode-menu/blob/fb1101481937635cc8006bacbd67ebfd08522247/unsafe-mode-menu%40linushdot.local/extension.js#L26)
- [via dconf setting](https://github.com/linushdot/unsafe-mode-menu/blob/fb1101481937635cc8006bacbd67ebfd08522247/unsafe-mode-menu%40linushdot.local/extension.js#L31) (see [Readme section](https://github.com/linushdot/unsafe-mode-menu?tab=readme-ov-file#changing-unsafe-mode-via-dconf))
- [enable when loading the extension, if configured](https://github.com/linushdot/unsafe-mode-menu/blob/fb1101481937635cc8006bacbd67ebfd08522247/unsafe-mode-menu%40linushdot.local/extension.js#L44) (line mentioned above)

> It's quite an itch [not having screensharing](https://askubuntu.com/questions/1407494/screen-share-not-working-in-ubuntu-22-04-in-all-platforms-zoom-teams-google-m/1408030#1408030) and this seems to be the most natural solution.

Personally, I do not have problems with screen sharing anymore since Zoom fixed their client (in [version 5.11.0](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0068973#01H84VGG3HV8GNK3EH8YNKMGTY)). Teams and Google Meet mentioned in the Askubuntu link also seem to work fine when using their web apps in a browser. What applications do you have trouble using screen sharing in?

In general, using unsafe mode for screen sharing is a workaround, not a solution. Most app developers should be able to fix their applications instead (they just need to use a [new API](https://flatpak.github.io/xdg-desktop-portal/), screen sharing is still possible with current gnome versions).

**Comment by matanox** [comment]
Oh, thanks again for the extension, and now also the reply. Your explanation makes perfect sense. 

Somehow Google Meet didn't work for me with the latest Chrome on Ubuntu 22.04, but I'll try the extension and also revisit it under gnome's default safe mode within a few system updates down the road, if it's working for you even without switching to gnome's unsafe mode.
